package com.oracle.xmlns.oxp.service.v2;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c 12.1.2.0.0.6668

import com.oracle.xmlns.oxp.service.v2.ParamNameValues; 
import com.oracle.xmlns.oxp.service.v2.ReportResponse;
import com.oracle.xmlns.oxp.service.v2.ReportService;
import com.oracle.xmlns.oxp.service.v2.*;

import java.util.Iterator;
import java.util.Map;
import java.util.Set;

public class ReportServiceClient {
    private static Object publicReportService;
    private String paramName; 
    private String paramValue;

    public static void main(String[] args) {
        ReportService_Service reportService_Service = new ReportService_Service();
        ReportService reportService = reportService_Service.getReportService();

        // Set up the credentials for our service call    
        String username = "weblogic";    
        String password = "weblogic";         
        
        // Instantiate a new ReportRequest object    
        ReportRequest repReq = new ReportRequest();         
        // Define the report that we want to run    
        repReq.setReportAbsolutePath("/Sample Lite/Published Reporting/Reports/Balance Letter.xdo"); // This is the Report name, as an absolute path.         
        // Define what we want to do with it    
        repReq.setAttributeFormat("pdf");  
        // The path on the **BIP server** to which the report should be saved  
        repReq.setReportOutputPath("/opt/oracle/middleware_home/obbie_file/Balance_Letter.pdf"); 
        // Output saved    
                           
        try {        
        reportService.runReport(repReq, username, password);    
        } catch (InvalidParametersException_Exception e) 
          {        System.out.println("Exception thrown: InvalidParameters!");    } 
          catch (AccessDeniedException_Exception e) 
          {        System.out.println("Exception thrown: AccessDenied!");    } 
           catch (OperationFailedException_Exception e)
          {        System.out.println("Exception thrown: OperationFailed!");    }    
        
        System.out.println("Success!");

        }
}
